server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /

##########################################################################
#                                 guns配置
##########################################################################
guns:
  #验证码开启
  kaptcha-open: true
  kaptcha-invalidate-time: 180
  swagger-open: false
#文件上传目录(不配置的话为java.io.tmpdir目录)
  file-upload-path: d:\\tmp
  #是否开启spring session,如果是多机环境需要开启(true/false)
  spring-session-open: true
  #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-invalidate-time: 1800
  #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  session-validation-interval: 900

spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-request-size: 100MB
      #文件上传大小限制
      max-file-size: 100MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

##########################################################################
#
# 开发环境配置
#
##########################################################################
  devtools:
    restart:
      enabled: false

##########################################################################
#                                 Redis配置
##########################################################################
  redis:
      database: 3
      password: ''
      # 连接超时时间(毫秒)
      timeout: 3000
      jedis:
        pool:
          max-active: 1000
          max-wait: -1
          max-idle: 10
          min-idle: 2

##########################################################################
#                                 日志配置
##########################################################################
logging:
  level.root: info
  level.org.tc: debug
  path: d:\\logs\\
  file: shiro-SBM.log

##########################################################################
#
# mybatis配置
#
##########################################################################
mybatis:
  type-aliases-package: org.tc.shiro.po
  mapper-locations: /mapper/**.xml
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true

##########################################################################
#
# mapper配置
#
##########################################################################
mapper:
  mappers:
    - org.tc.mybatis.dao.MyMapper
  not-empty: false
  identity: MYSQL


##########################################################################
#
# pagehelper配置
#
##########################################################################
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shiro?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
        #初始化物理连接个数，默认值0
        initial-size: 5
        # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
        max-wait: 60000
        # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        test-on-borrow: true
        # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        test-on-return: true
        # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
        validation-query: SELECT 'x'
        filters: wall,mergeStat

##########################################################################
#
# freemarker静态资源配置
#
##########################################################################
##########################################################################
  freemarker:
    enabled: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
#    expose-request-attributes: true
    expose-session-attributes: true
#    request-context-attribute: req
    cache: false